### ISSUE TITLE
토스트메세지를 만들어 볼까요?

### ISSUE THREAD

**Issue by na-reum** [sopt-makers/sopt-crew-frontend#392]
## ✨ Description
토스트 메세지를 만들어볼꺼에요. 

## ✅ To Do List
- [ ] 빵 반죽하기
- [ ] 반죽 발효하기
- [ ] 틀에 넣기
- [ ] 오븐에 굽기
- [ ] 자르기
- [ ] 토스트기에 넣기

**Comment by eunsukimme** [comment]
제빵사 폼 미쳤다~
