### ISSUE TITLE
피드 상세 뷰 게시글에 가로스크롤 생기는 이슈

### ISSUE THREAD

**Issue by eunsukimme** [sopt-makers/sopt-crew-frontend#470]
## ✨ Description
피드 상세 뷰 게시글에 가로스크롤 생기는 이슈

**Comment by 100Gyeon** [comment]
![image](https://github.com/sopt-makers/sopt-crew-frontend/assets/58380158/e756e13f-55d7-449a-862c-0a132f4848f2)

요거 내가 수정할게!
