### ISSUE TITLE
QA 반영해 자잘한 스타일 오류 수정

### ISSUE THREAD

**Issue by borimong** [sopt-makers/sopt-crew-frontend#485]
## ✨ Description
구현할 기능 작성

이슈 02
단락을 나누어 글을 작성했는데 붙어버리는 이슈 발생 (/n 적용이 필요한걸까나?!)

이슈 07
피드에 이미지 첨부 시 이미지와 조회수 right align이 맞지 않아요
padding값이 40px이어야 합니다
지금 padding은 이미지 49px, 조회수 40px 으로 상이

이슈 08 (cr-fe)
패딩이 이중으로 들어가있는 것 같습니다!
MO에서 이런 이유로 인해 댓글 영역이 많이 좁아졌어용

이슈 12
댓글 input이 고정되어있지 않고 날아가요
(사파리 기준) 왼쪽 12 pro, 오른쪽 14 pro

**Comment by na-reum** [comment]
이거 다 끝났나요?
